language: "node_js"
os:
  - linux
node_js:
  - "10"
cache:
  yarn: true
install:
  - yarn install
script:
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: ./build
  on:
    branch: master
