language: node_js
node_js:
  - "10"

cache:
  yarn: true
  directories:
    - "client/build"

install:
  - yarn install

jobs:
  include:
    - stage: test
      script:
        - npm run test
    - stage: react
      before_install:
        - cd client
      script:
        - npm run build
