language: "node_js"
os:
  - linux
node_js:
  - "10"
cache: npm
stages:
  - deploy-gh-pages
  - docker
jobs:
  include:
    - stage: deploy-gh-pages
      install:
        - npm install
      script:
        - npm run build:prod
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        local_dir: ./build
        on:
          branch: master
    - if: branch = master
      stage: docker
      install:
        - npm install
      script:
        - npm run build:prod
        - docker login --username $DOCKER_USER -p $DOCKER_PASS
        - docker build -t rctechclub/ladybird:prod .
        - docker push rctechclub/ladybird:prod

    - stage: docker
      install:
        - npm install
      script:
        - npm run build:dev
        - docker login --username $DOCKER_USER -p $DOCKER_PASS
        - docker build -t rctechclub/ladybird:latest .
        - docker push rctechclub/ladybird:latest
