name: Deploy Ladybird

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Use NodeJS stable
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install
        run: npm install

      - name: Build for production
        run: npm run build:prod

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push prod to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: rctechclub/ladybird:prod

      - name: Push latest to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: rctechclub/ladybird:latest
